### ISSUE TITLE
MySql option to use prefix in key names is missing

### ISSUE THREAD

**Issue by petarsupica** [RobertArtigas/DCT2SQL#1]
MySql option to use prefix in key names is missing in latest mysql script generator.
D2M1_Mysql
Can You please add that option?

**Comment by RobertArtigas** [comment]
The original template still has that option and it is still included in the current template collection. Just un-comment that older template and you will have it available. The newer templates are used for my conversion consulting projects (paid work) and so far that option has not come up as being needed yet. So it has not been coded at this time. You are also more than welcome to add the option to the current set of templates.
